// ============ WESTAY NEW FEATURES ============
// 1. Owner Monthly Report (per-landlord, Homelette-style)
// 2. Tenant Utility Bill (auto-generate from meter readings)
// 3. Photo Attachments (tickets + check-in/check-out)

// ============================================================
// 1. OWNER MONTHLY REPORT — Per-Landlord Property Report
// ============================================================

function generateOwnerReport(landlordName) {
  // If no landlord specified, show selection
  if (!landlordName) {
    const opts = LANDLORDS.map(ll => '<option value="' + escHtml(ll.n) + '">' + escHtml(ll.n) + ' — ' + ll.props.join(', ') + '</option>').join('');
    openModal('<i class="fas fa-file-alt" style="color:#FD79A8"></i> Generate Owner Report',
      '<div style="font-size:12px;color:var(--t2);margin-bottom:14px">Select a landlord/owner to generate their monthly property report with income, expenses, and net rental breakdown.</div>' +
      '<div class="form-group"><label>Select Owner</label><select id="ownerReportSel">' + opts + '</select></div>',
      '<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>' +
      '<button class="btn btn-p" onclick="closeModal();generateOwnerReport(document.getElementById(\'ownerReportSel\').value)"><i class="fas fa-file-alt"></i> Generate</button>', 'sm');
    return;
  }

  const ll = LANDLORDS.find(l => l.n === landlordName);
  if (!ll) { toast('Owner not found', 'error'); return; }

  const now = new Date();
  const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  const month = monthNames[now.getMonth()];
  const year = now.getFullYear();

  // Collect data per property
  let totalIncome = 0, totalExpenses = 0;
  const propData = [];

  ll.props.forEach(propName => {
    const prop = PROPS.find(p => p.n === propName);
    if (!prop) return;

    // Income = tenants in this property
    const propTenants = TENANTS.filter(t => t.p.includes(propName));
    const roomIncomes = [];
    let propRentIncome = 0;

    propTenants.forEach(t => {
      const rent = parseInt(t.r.replace(/[^\d]/g, '')) || 0;
      const room = t.p.replace(propName, '').trim();
      roomIncomes.push({ tenant: t.n, room: room || t.p, rent: rent, status: t.s });
      if (t.s === 'active') propRentIncome += rent;
    });

    // Utility income from meters
    const propElecMeters = ELECTRIC_METERS.filter(m => m.unit === propName && m.tenant);
    const propWaterMeters = WATER_METERS.filter(m => m.unit === propName && m.tenant);
    let utilityIncome = 0;
    const utilityDetails = [];

    propElecMeters.forEach(m => {
      const amt = Math.round(m.kwh * UTILITY_RATES.electric.rate * 100) / 100;
      utilityIncome += amt;
      utilityDetails.push({ tenant: m.tenant, room: m.room, type: 'Electric', usage: m.kwh + ' kWh', amount: amt });
    });
    propWaterMeters.forEach(m => {
      const amt = Math.round(m.m3 * UTILITY_RATES.water.rate * 100) / 100;
      utilityIncome += amt;
      utilityDetails.push({ tenant: m.tenant, room: m.room, type: 'Water', usage: m.m3 + ' m\u00B3', amount: amt });
    });

    // Expenses
    const expenses = PROPERTY_EXPENSES[propName] || {};
    const totalPropExpense = Object.values(expenses).reduce((s, v) => s + v, 0);

    const propTotalIncome = propRentIncome + Math.round(utilityIncome);
    totalIncome += propTotalIncome;
    totalExpenses += totalPropExpense;

    propData.push({
      name: propName,
      prop: prop,
      tenants: propTenants,
      roomIncomes: roomIncomes,
      rentIncome: propRentIncome,
      utilityIncome: Math.round(utilityIncome),
      utilityDetails: utilityDetails,
      totalIncome: propTotalIncome,
      expenses: expenses,
      totalExpense: totalPropExpense,
      netRental: propTotalIncome - totalPropExpense
    });
  });

  const netRental = totalIncome - totalExpenses;

  // Build report HTML
  let html = '<div style="max-width:700px;margin:0 auto">';

  // Header
  html += '<div style="background:linear-gradient(135deg,#FD79A8,#6C5CE7);padding:28px;border-radius:16px;text-align:center;margin-bottom:20px">' +
    '<div style="font-size:32px;margin-bottom:6px">\uD83C\uDFE0</div>' +
    '<h2 style="color:#fff;font-size:18px;margin-bottom:2px">LANDLORD PROPERTY REPORT</h2>' +
    '<div style="color:rgba(255,255,255,.85);font-size:14px;font-weight:600">' + escHtml(ll.n) + '</div>' +
    '<div style="color:rgba(255,255,255,.6);font-size:11px;margin-top:4px">' + month + ' ' + year + ' &bull; Auto-generated by WeStay</div></div>';

  // Summary Cards
  html += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-bottom:18px">' +
    ownerReportKPI('RM ' + totalIncome.toLocaleString(), 'Total Collection', '#00B894') +
    ownerReportKPI('RM ' + totalExpenses.toLocaleString(), 'Total Expenses', '#E17055') +
    ownerReportKPI('RM ' + netRental.toLocaleString(), 'Net Rental', netRental >= 0 ? '#6C5CE7' : '#E17055') +
    '</div>';

  // Per-Property Breakdown
  propData.forEach(pd => {
    html += '<div style="background:var(--bg3);border-radius:14px;padding:18px;margin-bottom:16px;border-left:3px solid ' + pd.prop.c + '">';

    // Property header
    html += '<div style="display:flex;align-items:center;gap:10px;margin-bottom:14px">' +
      '<div style="width:36px;height:36px;border-radius:10px;background:' + pd.prop.c + '22;color:' + pd.prop.c + ';display:flex;align-items:center;justify-content:center;font-size:16px"><i class="fas ' + pd.prop.icon + '"></i></div>' +
      '<div style="flex:1"><div style="font-size:14px;font-weight:700">' + escHtml(pd.name) + '</div>' +
      '<div style="font-size:10px;color:var(--t3)">' + pd.prop.r + ' rooms &bull; ' + pd.prop.o + '% occupancy</div></div>' +
      '<div style="text-align:right"><div style="font-size:14px;font-weight:700;color:' + (pd.netRental >= 0 ? 'var(--ok)' : 'var(--err)') + '">RM ' + pd.netRental.toLocaleString() + '</div>' +
      '<div style="font-size:9px;color:var(--t3)">Net Rental</div></div></div>';

    // Room Income Table
    html += '<div style="margin-bottom:12px"><div style="font-size:11px;font-weight:600;margin-bottom:6px;color:var(--t2)"><i class="fas fa-coins" style="color:var(--ok);margin-right:6px"></i>INCOME — Room Rental</div>';
    if (pd.roomIncomes.length) {
      html += '<table style="margin:0"><thead><tr><th>Room</th><th>Tenant</th><th>Rent (RM)</th><th>Status</th></tr></thead><tbody>';
      pd.roomIncomes.forEach(ri => {
        const cls = ri.status === 'active' ? 'b-ok' : ri.status === 'pending' ? 'b-warn' : 'b-err';
        html += '<tr><td>' + escHtml(ri.room) + '</td><td>' + escHtml(ri.tenant) + '</td><td style="font-weight:600">RM ' + ri.rent + '</td><td><span class="bs ' + cls + '">' + escHtml(ri.status) + '</span></td></tr>';
      });
      html += '<tr style="background:var(--bg2)"><td colspan="2" style="font-weight:600;text-align:right">Subtotal Rent</td><td colspan="2" style="font-weight:700;color:var(--ok)">RM ' + pd.rentIncome.toLocaleString() + '</td></tr>';
      html += '</tbody></table>';
    } else {
      html += '<div style="font-size:11px;color:var(--t3);padding:8px">No tenants currently</div>';
    }
    html += '</div>';

    // Utility Income
    if (pd.utilityDetails.length) {
      html += '<div style="margin-bottom:12px"><div style="font-size:11px;font-weight:600;margin-bottom:6px;color:var(--t2)"><i class="fas fa-bolt" style="color:var(--warn);margin-right:6px"></i>INCOME — Utilities</div>';
      html += '<table style="margin:0"><thead><tr><th>Room</th><th>Tenant</th><th>Type</th><th>Usage</th><th>Amount</th></tr></thead><tbody>';
      pd.utilityDetails.forEach(ud => {
        html += '<tr><td>' + escHtml(ud.room) + '</td><td>' + escHtml(ud.tenant) + '</td><td>' + escHtml(ud.type) + '</td><td>' + escHtml(ud.usage) + '</td><td style="font-weight:600">RM ' + ud.amount.toFixed(2) + '</td></tr>';
      });
      html += '<tr style="background:var(--bg2)"><td colspan="4" style="font-weight:600;text-align:right">Subtotal Utility</td><td style="font-weight:700;color:var(--ok)">RM ' + pd.utilityIncome.toLocaleString() + '</td></tr>';
      html += '</tbody></table></div>';
    }

    // Expenses Table
    html += '<div style="margin-bottom:12px"><div style="font-size:11px;font-weight:600;margin-bottom:6px;color:var(--t2)"><i class="fas fa-receipt" style="color:var(--err);margin-right:6px"></i>EXPENSES</div>';
    html += '<table style="margin:0"><thead><tr><th>Category</th><th style="text-align:right">Amount (RM)</th></tr></thead><tbody>';
    const expLabels = { mgmtFee: 'Management Fee', maintenance: 'Maintenance & Repair', internet: 'Internet / WiFi', cleaning: 'Cleaning Service', insurance: 'Insurance', misc: 'Miscellaneous' };
    Object.keys(pd.expenses).forEach(key => {
      html += '<tr><td>' + (expLabels[key] || key) + '</td><td style="text-align:right;font-weight:600;color:var(--err)">RM ' + pd.expenses[key].toLocaleString() + '</td></tr>';
    });
    html += '<tr style="background:var(--bg2)"><td style="font-weight:600;text-align:right">Total Expenses</td><td style="text-align:right;font-weight:700;color:var(--err)">RM ' + pd.totalExpense.toLocaleString() + '</td></tr>';
    html += '</tbody></table></div>';

    // Net Summary
    html += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;padding:12px;background:var(--bg2);border-radius:10px">' +
      '<div style="text-align:center"><div style="font-size:9px;color:var(--t3)">Total Income</div><div style="font-size:14px;font-weight:700;color:var(--ok)">RM ' + pd.totalIncome.toLocaleString() + '</div></div>' +
      '<div style="text-align:center"><div style="font-size:9px;color:var(--t3)">Total Expenses</div><div style="font-size:14px;font-weight:700;color:var(--err)">RM ' + pd.totalExpense.toLocaleString() + '</div></div>' +
      '<div style="text-align:center"><div style="font-size:9px;color:var(--t3)">Net Rental</div><div style="font-size:14px;font-weight:700;color:' + (pd.netRental >= 0 ? 'var(--ok)' : 'var(--err)') + '">RM ' + pd.netRental.toLocaleString() + '</div></div></div>';

    html += '</div>';
  });

  // Grand Summary
  html += '<div style="background:linear-gradient(135deg,#6C5CE722,#FD79A822);border:1px solid #6C5CE744;border-radius:14px;padding:18px;margin-bottom:16px">' +
    '<h4 style="font-size:14px;margin-bottom:12px"><i class="fas fa-calculator" style="color:var(--p);margin-right:8px"></i>Summary of Collection & Expenses</h4>' +
    '<div class="dep-card" style="background:var(--bg2)">' +
    depRow('Total Rental Collection', 'RM ' + propData.reduce((s, p) => s + p.rentIncome, 0).toLocaleString()) +
    depRow('Total Utility Collection', 'RM ' + propData.reduce((s, p) => s + p.utilityIncome, 0).toLocaleString()) +
    depRowHtml('Total Income', '<span style="font-weight:700;color:var(--ok)">RM ' + totalIncome.toLocaleString() + '</span>') +
    depRow('Total Expenses', 'RM ' + totalExpenses.toLocaleString()) +
    depRowHtml('Net Rental (Payout)', '<span style="font-size:16px;font-weight:800;color:' + (netRental >= 0 ? 'var(--ok)' : 'var(--err)') + '">RM ' + netRental.toLocaleString() + '</span>') +
    '</div></div>';

  // Footer
  html += '<div style="text-align:center;padding:14px;font-size:10px;color:var(--t3)">' +
    'Report auto-generated by WeStay AI &bull; ' + now.toLocaleDateString('en-MY') + ' ' + now.toLocaleTimeString('en-MY') +
    '<br>For enquiries, contact admin@westay.my</div></div>';

  // Open in modal
  openModal('<i class="fas fa-file-alt" style="color:#FD79A8"></i> Owner Report — ' + escHtml(ll.n), html,
    '<button class="btn btn-ghost" onclick="closeModal()">Close</button>' +
    '<button class="btn btn-p" onclick="downloadOwnerReportCSV(\'' + landlordName.replace(/'/g, "\\'") + '\')"><i class="fas fa-download"></i> Download CSV</button>' +
    '<button class="btn" style="background:#00B894;color:#fff" onclick="printOwnerReport()"><i class="fas fa-print"></i> Print / PDF</button>', 'lg');

  toast('Owner report generated for ' + escHtml(ll.n), 'success');
  pushNotif('fa-file-alt', '#FD79A8', 'Owner Report Generated', escHtml(ll.n) + ' — ' + month + ' ' + year);
}

function ownerReportKPI(val, label, color) {
  return '<div style="text-align:center;padding:14px;background:var(--bg3);border-radius:12px;border-left:3px solid ' + color + '">' +
    '<div style="font-size:18px;font-weight:800;color:' + color + '">' + val + '</div>' +
    '<div style="font-size:10px;color:var(--t3);margin-top:2px">' + label + '</div></div>';
}

function downloadOwnerReportCSV(landlordName) {
  const ll = LANDLORDS.find(l => l.n === landlordName);
  if (!ll) return;
  const headers = ['Property', 'Category', 'Description', 'Amount (RM)'];
  const rows = [];
  ll.props.forEach(propName => {
    const propTenants = TENANTS.filter(t => t.p.includes(propName) && t.s === 'active');
    propTenants.forEach(t => {
      rows.push([propName, 'Rental Income', t.n + ' — ' + t.p, parseInt(t.r.replace(/[^\d]/g, '')) || 0]);
    });
    const expenses = PROPERTY_EXPENSES[propName] || {};
    const expLabels = { mgmtFee: 'Management Fee', maintenance: 'Maintenance', internet: 'Internet', cleaning: 'Cleaning', insurance: 'Insurance', misc: 'Misc' };
    Object.keys(expenses).forEach(key => {
      rows.push([propName, 'Expense', expLabels[key] || key, -expenses[key]]);
    });
  });
  exportCSV(headers, rows, 'westay-owner-report-' + landlordName.replace(/\s+/g, '-').toLowerCase() + '-' + new Date().toISOString().slice(0, 7) + '.csv');
}

function printOwnerReport() {
  const modalBody = document.querySelector('.modal-body');
  if (!modalBody) return;
  const w = window.open('', '_blank', 'noopener,noreferrer');
  w.document.write('<html><head><title>Owner Monthly Report</title><style>body{font-family:system-ui,-apple-system,sans-serif;background:#1a1929;color:#e2e0f0;padding:30px;max-width:750px;margin:0 auto}*{box-sizing:border-box}table{width:100%;border-collapse:collapse}th,td{padding:8px 10px;text-align:left;border-bottom:1px solid #2D2B4A;font-size:11px}</style></head><body>' + modalBody.innerHTML + '</body></html>');
  w.document.close();
  setTimeout(function() { w.print(); }, 500);
}


// ============================================================
// 2. TENANT UTILITY BILL — Auto-Generate from Meter Readings
// ============================================================

function generateUtilityBills() {
  const now = new Date();
  const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  const month = monthNames[now.getMonth()];
  const year = now.getFullYear();
  const billingPeriod = month + ' ' + year;

  // Check if already generated for this month
  const existingBill = UTILITY_BILLS.find(b => b.period === billingPeriod);
  if (existingBill) {
    toast('Utility bills already generated for ' + billingPeriod, 'info');
    showUtilityBillList();
    return;
  }

  let count = 0;

  TENANTS.forEach(t => {
    if (t.s !== 'active') return;

    const propName = t.p.split(' ')[0];

    // Electric meter reading
    const elecMeter = ELECTRIC_METERS.find(m => m.tenant === t.n);
    const elecKwh = elecMeter ? elecMeter.kwh : 0;
    const elecAmt = Math.round(elecKwh * UTILITY_RATES.electric.rate * 100) / 100;

    // Water meter reading
    const waterMeter = WATER_METERS.find(m => m.tenant === t.n);
    const waterM3 = waterMeter ? waterMeter.m3 : 0;
    const waterAmt = Math.round(waterM3 * UTILITY_RATES.water.rate * 100) / 100;

    // Internet (flat rate per room)
    const internetAmt = UTILITY_RATES.internet.rate;

    // Sewerage (flat rate)
    const sewerageAmt = UTILITY_RATES.sewerage.rate;

    const totalAmt = Math.round((elecAmt + waterAmt + internetAmt + sewerageAmt) * 100) / 100;

    const billId = 'UB-' + year + String(now.getMonth() + 1).padStart(2, '0') + '-' + String(UTILITY_BILLS.length + count + 1).padStart(3, '0');

    UTILITY_BILLS.push({
      id: billId,
      tenant: t.n,
      unit: t.p,
      property: propName,
      period: billingPeriod,
      date: now.toISOString().slice(0, 10),
      items: [
        { type: 'Electricity', usage: elecKwh, unit: 'kWh', rate: UTILITY_RATES.electric.rate, amount: elecAmt, meterId: elecMeter ? elecMeter.meterId : 'N/A' },
        { type: 'Water', usage: waterM3, unit: 'm\u00B3', rate: UTILITY_RATES.water.rate, amount: waterAmt, meterId: waterMeter ? waterMeter.meterId : 'N/A' },
        { type: 'Internet', usage: 1, unit: 'month', rate: UTILITY_RATES.internet.rate, amount: internetAmt, meterId: 'Flat' },
        { type: 'Sewerage', usage: 1, unit: 'month', rate: UTILITY_RATES.sewerage.rate, amount: sewerageAmt, meterId: 'Flat' }
      ],
      total: totalAmt,
      status: 'Pending'
    });
    count++;
  });

  saveData();
  toast(count + ' utility bill(s) generated for ' + billingPeriod, 'success');
  pushNotif('fa-file-invoice', '#74B9FF', 'Utility Bills Generated', count + ' bills for ' + billingPeriod);
  showUtilityBillList();
}

function showUtilityBillList() {
  let html = '<div style="margin-bottom:14px;display:flex;align-items:center;justify-content:space-between">' +
    '<div style="font-size:12px;color:var(--t2)"><i class="fas fa-info-circle" style="color:var(--p);margin-right:6px"></i>Utility bills are calculated from sub-meter readings (electric, water) plus flat-rate services (internet, sewerage).</div>' +
    '<button class="btn btn-p" style="flex-shrink:0" onclick="closeModal();generateUtilityBills()"><i class="fas fa-sync"></i> Generate</button></div>';

  if (!UTILITY_BILLS.length) {
    html += '<div class="empty-state"><i class="fas fa-file-invoice"></i><p>No utility bills generated yet. Click "Generate" to create bills from meter readings.</p></div>';
  } else {
    // Summary
    const totalPending = UTILITY_BILLS.filter(b => b.status === 'Pending').length;
    const totalPaid = UTILITY_BILLS.filter(b => b.status === 'Paid').length;
    const totalAmt = UTILITY_BILLS.reduce((s, b) => s + b.total, 0);

    html += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-bottom:16px">' +
      '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--p)">' + UTILITY_BILLS.length + '</div><div style="font-size:10px;color:var(--t3)">Total Bills</div></div>' +
      '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--warn)">' + totalPending + '</div><div style="font-size:10px;color:var(--t3)">Pending</div></div>' +
      '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--ok)">RM ' + totalAmt.toFixed(2) + '</div><div style="font-size:10px;color:var(--t3)">Total Amount</div></div></div>';

    // Bills table
    html += '<table><thead><tr><th>Bill ID</th><th>Tenant</th><th>Unit</th><th>Period</th><th>Total (RM)</th><th>Status</th><th></th></tr></thead><tbody>';
    UTILITY_BILLS.forEach(bill => {
      const cls = bill.status === 'Paid' ? 'b-ok' : 'b-warn';
      html += '<tr><td style="font-weight:600">' + escHtml(bill.id) + '</td>' +
        '<td>' + escHtml(bill.tenant) + '</td>' +
        '<td>' + escHtml(bill.unit) + '</td>' +
        '<td>' + escHtml(bill.period) + '</td>' +
        '<td style="font-weight:600">RM ' + bill.total.toFixed(2) + '</td>' +
        '<td><span class="bs ' + cls + '">' + escHtml(bill.status) + '</span></td>' +
        '<td><button class="btn-s" onclick="showUtilityBillDetail(\'' + bill.id + '\')"><i class="fas fa-eye"></i></button>' +
        (bill.status !== 'Paid' ? ' <button class="btn-s" onclick="payUtilityBill(\'' + bill.id + '\')"><i class="fas fa-credit-card"></i></button>' : '') +
        '</td></tr>';
    });
    html += '</tbody></table>';
  }

  openModal('<i class="fas fa-bolt" style="color:#74B9FF"></i> Tenant Utility Bills', html, '<button class="btn btn-ghost" onclick="closeModal()">Close</button>' +
    '<button class="btn btn-p" onclick="exportUtilityBillsCSV()"><i class="fas fa-download"></i> Export CSV</button>', 'lg');
}

function showUtilityBillDetail(billId) {
  const bill = UTILITY_BILLS.find(b => b.id === billId);
  if (!bill) { toast('Bill not found', 'error'); return; }

  let html = '<div style="max-width:500px;margin:0 auto">';

  // Bill header
  html += '<div style="background:linear-gradient(135deg,#74B9FF,#6C5CE7);padding:24px;border-radius:16px;text-align:center;margin-bottom:18px">' +
    '<div style="font-size:28px;margin-bottom:4px">\u26A1</div>' +
    '<h3 style="color:#fff;font-size:16px;margin-bottom:2px">UTILITY BILL</h3>' +
    '<div style="color:rgba(255,255,255,.7);font-size:12px">' + escHtml(bill.id) + ' &bull; ' + escHtml(bill.period) + '</div></div>';

  // Tenant info
  html += '<div class="dep-card">' +
    depRow('Tenant', escHtml(bill.tenant)) +
    depRow('Unit', escHtml(bill.unit)) +
    depRow('Billing Period', escHtml(bill.period)) +
    depRow('Bill Date', escHtml(bill.date)) +
    depRowHtml('Status', '<span class="bs ' + (bill.status === 'Paid' ? 'b-ok' : 'b-warn') + '">' + escHtml(bill.status) + '</span>') +
    '</div>';

  // Items breakdown
  html += '<div style="margin:14px 0"><div style="font-size:12px;font-weight:600;margin-bottom:8px"><i class="fas fa-list" style="color:var(--p);margin-right:6px"></i>Charge Breakdown</div>';
  html += '<table><thead><tr><th>Type</th><th>Usage</th><th>Rate</th><th>Meter ID</th><th style="text-align:right">Amount</th></tr></thead><tbody>';
  bill.items.forEach(item => {
    const typeIcon = item.type === 'Electricity' ? '\u26A1' : item.type === 'Water' ? '\uD83D\uDCA7' : item.type === 'Internet' ? '\uD83C\uDF10' : '\uD83D\uDEB0';
    html += '<tr><td>' + typeIcon + ' ' + escHtml(item.type) + '</td>' +
      '<td>' + item.usage + ' ' + escHtml(item.unit) + '</td>' +
      '<td>RM ' + item.rate.toFixed(3) + '/' + escHtml(item.unit) + '</td>' +
      '<td style="font-family:monospace;font-size:10px">' + escHtml(item.meterId) + '</td>' +
      '<td style="text-align:right;font-weight:600">RM ' + item.amount.toFixed(2) + '</td></tr>';
  });
  html += '<tr style="background:var(--bg2)"><td colspan="4" style="font-weight:700;text-align:right">TOTAL</td>' +
    '<td style="text-align:right;font-size:16px;font-weight:800;color:var(--p)">RM ' + bill.total.toFixed(2) + '</td></tr>';
  html += '</tbody></table></div>';

  // Rate reference
  html += '<div style="padding:10px;background:var(--bg3);border-radius:10px;font-size:10px;color:var(--t3)">' +
    '<strong>Rate Reference:</strong> Electric: RM ' + UTILITY_RATES.electric.rate + '/kWh (TNB tariff) &bull; ' +
    'Water: RM ' + UTILITY_RATES.water.rate + '/m\u00B3 &bull; ' +
    'Internet: RM ' + UTILITY_RATES.internet.rate + '/month &bull; ' +
    'Sewerage: RM ' + UTILITY_RATES.sewerage.rate + '/month</div>';

  html += '</div>';

  closeModal();
  setTimeout(function() {
    openModal('<i class="fas fa-file-invoice" style="color:#74B9FF"></i> Utility Bill — ' + escHtml(bill.tenant), html,
      '<button class="btn btn-ghost" onclick="closeModal();showUtilityBillList()">Back</button>' +
      (bill.status !== 'Paid' ? '<button class="btn btn-p" onclick="payUtilityBill(\'' + bill.id + '\')"><i class="fas fa-credit-card"></i> Pay</button>' : '') +
      '<button class="btn" style="background:#00B894;color:#fff" onclick="printUtilityBill()"><i class="fas fa-print"></i> Print</button>', 'sm');
  }, 200);
}

function payUtilityBill(billId) {
  const bill = UTILITY_BILLS.find(b => b.id === billId);
  if (!bill) return;
  confirmDialog('Pay Utility Bill', 'Process payment of RM ' + bill.total.toFixed(2) + ' for ' + escHtml(bill.tenant) + '?', function() {
    bill.status = 'Paid';
    saveData();
    toast('Utility bill ' + escHtml(bill.id) + ' paid!', 'success');
    pushNotif('fa-credit-card', '#00B894', 'Utility Bill Paid', escHtml(bill.tenant) + ' — RM ' + bill.total.toFixed(2));
    closeModal();
    setTimeout(showUtilityBillList, 200);
  }, 'success');
}

function exportUtilityBillsCSV() {
  const headers = ['Bill ID', 'Tenant', 'Unit', 'Period', 'Electricity (RM)', 'Water (RM)', 'Internet (RM)', 'Sewerage (RM)', 'Total (RM)', 'Status'];
  const rows = UTILITY_BILLS.map(b => {
    const getAmt = function(type) { var item = b.items.find(function(i) { return i.type === type; }); return item ? item.amount.toFixed(2) : '0.00'; };
    return [b.id, b.tenant, b.unit, b.period, getAmt('Electricity'), getAmt('Water'), getAmt('Internet'), getAmt('Sewerage'), b.total.toFixed(2), b.status];
  });
  exportCSV(headers, rows, 'westay-utility-bills-' + new Date().toISOString().slice(0, 7) + '.csv');
}

function printUtilityBill() {
  var modalBody = document.querySelector('.modal-body');
  if (!modalBody) return;
  var w = window.open('', '_blank', 'noopener,noreferrer');
  w.document.write('<html><head><title>Utility Bill</title><style>body{font-family:system-ui,-apple-system,sans-serif;background:#1a1929;color:#e2e0f0;padding:30px;max-width:600px;margin:0 auto}*{box-sizing:border-box}table{width:100%;border-collapse:collapse}th,td{padding:8px 10px;text-align:left;border-bottom:1px solid #2D2B4A;font-size:11px}</style></head><body>' + modalBody.innerHTML + '</body></html>');
  w.document.close();
  setTimeout(function() { w.print(); }, 500);
}

// ============================================================
// PAYMENT GATEWAY — Tenant Online Payment Simulation
// ============================================================

function tenantPayWithGateway(billType, billId) {
  var bill, amount, label;
  if (billType === 'rent') {
    bill = BILLS.find(function(b) { return b.id === billId; });
    if (!bill || bill.s === 'Paid') { toast('Bill already paid or not found', 'info'); return; }
    amount = parseInt(bill.a.replace(/[^\d]/g, '')) || 0;
    label = 'Rent — ' + escHtml(bill.id);
  } else {
    bill = UTILITY_BILLS.find(function(b) { return b.id === billId; });
    if (!bill || bill.status === 'Paid') { toast('Bill already paid or not found', 'info'); return; }
    amount = bill.total;
    label = 'Utility — ' + escHtml(bill.id);
  }

  var html = '<div style="max-width:420px;margin:0 auto">';
  // Gateway header
  html += '<div style="background:linear-gradient(135deg,#6C5CE7,#00B894);padding:22px;border-radius:16px;text-align:center;margin-bottom:18px">' +
    '<div style="font-size:28px;margin-bottom:4px">\uD83D\uDD12</div>' +
    '<h3 style="color:#fff;font-size:15px;margin-bottom:2px">SECURE PAYMENT</h3>' +
    '<div style="color:rgba(255,255,255,.7);font-size:11px">WeStay Payment Gateway &bull; 256-bit SSL</div></div>';

  // Amount display
  html += '<div style="text-align:center;padding:18px;background:var(--bg3);border-radius:14px;margin-bottom:16px">' +
    '<div style="font-size:10px;color:var(--t3);margin-bottom:4px">' + label + '</div>' +
    '<div style="font-size:32px;font-weight:800;color:var(--p)">RM ' + amount.toFixed(2) + '</div></div>';

  // Payment method selection
  html += '<div style="font-size:12px;font-weight:600;margin-bottom:10px"><i class="fas fa-wallet" style="color:var(--p);margin-right:6px"></i>Payment Method</div>';
  html += '<div id="pgMethods" style="display:grid;gap:8px;margin-bottom:16px">';
  var methods = [
    { id: 'fpx', icon: 'fa-university', name: 'FPX Online Banking', desc: 'Pay via Malaysian banks', color: '#00B894' },
    { id: 'card', icon: 'fa-credit-card', name: 'Credit / Debit Card', desc: 'Visa, Mastercard, AMEX', color: '#6C5CE7' },
    { id: 'ewallet', icon: 'fa-mobile-alt', name: 'E-Wallet', desc: 'Touch n Go, GrabPay, Boost', color: '#FDCB6E' },
    { id: 'qr', icon: 'fa-qrcode', name: 'DuitNow QR', desc: 'Scan QR code to pay', color: '#00CEC9' }
  ];
  methods.forEach(function(m) {
    html += '<div id="pgm-' + m.id + '" style="display:flex;align-items:center;gap:12px;padding:14px;background:var(--bg3);border:2px solid transparent;border-radius:12px;cursor:pointer;transition:.2s" onclick="selectPaymentMethod(\'' + m.id + '\')" onmouseover="this.style.background=\'var(--card)\'" onmouseout="if(!this.classList.contains(\'pg-sel\'))this.style.background=\'var(--bg3)\'">' +
      '<div style="width:40px;height:40px;border-radius:10px;background:' + m.color + '22;color:' + m.color + ';display:flex;align-items:center;justify-content:center;font-size:16px"><i class="fas ' + m.icon + '"></i></div>' +
      '<div style="flex:1"><div style="font-size:12px;font-weight:600">' + m.name + '</div>' +
      '<div style="font-size:10px;color:var(--t3)">' + m.desc + '</div></div>' +
      '<div style="width:18px;height:18px;border-radius:50%;border:2px solid var(--bg2)" id="pgr-' + m.id + '"></div></div>';
  });
  html += '</div>';

  // FPX bank selector (hidden by default)
  html += '<div id="pgFpxBanks" style="display:none;margin-bottom:16px">' +
    '<div class="form-group"><label>Select Your Bank</label>' +
    '<select id="pgBankSel"><option value="">-- Select Bank --</option>' +
    '<option>Maybank2u</option><option>CIMB Clicks</option><option>Public Bank</option>' +
    '<option>RHB Now</option><option>Hong Leong Connect</option><option>AmOnline</option>' +
    '<option>Bank Islam</option><option>Bank Rakyat</option><option>BSN</option>' +
    '<option>OCBC Online</option><option>HSBC Online</option><option>UOB</option></select></div></div>';

  // Card form (hidden by default)
  html += '<div id="pgCardForm" style="display:none;margin-bottom:16px">' +
    '<div class="form-group"><label>Card Number</label><input id="pgCardNum" placeholder="4111 1111 1111 1111" maxlength="19"></div>' +
    '<div class="form-row"><div class="form-group"><label>Expiry</label><input id="pgCardExp" placeholder="MM/YY" maxlength="5"></div>' +
    '<div class="form-group"><label>CVV</label><input id="pgCardCvv" placeholder="123" maxlength="4" type="password"></div></div>' +
    '<div class="form-group"><label>Cardholder Name</label><input id="pgCardName" placeholder="Name on card"></div></div>';

  // E-wallet selector (hidden by default)
  html += '<div id="pgEwalletSel" style="display:none;margin-bottom:16px">' +
    '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px">' +
    '<div style="padding:14px;background:var(--bg3);border-radius:10px;text-align:center;cursor:pointer;border:2px solid transparent" onclick="this.style.borderColor=\'var(--p)\'" id="ew-tng"><div style="font-size:18px;margin-bottom:4px">\uD83D\uDCB3</div><div style="font-size:10px;font-weight:600">Touch n Go</div></div>' +
    '<div style="padding:14px;background:var(--bg3);border-radius:10px;text-align:center;cursor:pointer;border:2px solid transparent" onclick="this.style.borderColor=\'var(--p)\'" id="ew-grab"><div style="font-size:18px;margin-bottom:4px">\uD83D\uDE97</div><div style="font-size:10px;font-weight:600">GrabPay</div></div>' +
    '<div style="padding:14px;background:var(--bg3);border-radius:10px;text-align:center;cursor:pointer;border:2px solid transparent" onclick="this.style.borderColor=\'var(--p)\'" id="ew-boost"><div style="font-size:18px;margin-bottom:4px">\uD83D\uDE80</div><div style="font-size:10px;font-weight:600">Boost</div></div></div></div>';

  // QR code (hidden by default)
  html += '<div id="pgQrDisplay" style="display:none;text-align:center;margin-bottom:16px">' +
    '<div style="width:180px;height:180px;margin:0 auto;background:var(--bg3);border-radius:14px;display:flex;align-items:center;justify-content:center;border:2px solid var(--p)">' +
    '<div><i class="fas fa-qrcode" style="font-size:80px;color:var(--p)"></i>' +
    '<div style="font-size:9px;color:var(--t3);margin-top:6px">Scan with DuitNow</div></div></div>' +
    '<div style="font-size:10px;color:var(--t3);margin-top:8px">QR code expires in 15 minutes</div></div>';

  // Security badge
  html += '<div style="display:flex;align-items:center;gap:8px;padding:10px;background:var(--bg3);border-radius:10px;margin-bottom:14px">' +
    '<i class="fas fa-shield-alt" style="color:var(--ok);font-size:14px"></i>' +
    '<div style="font-size:10px;color:var(--t3)">Secured by WeStay Payment Gateway &bull; PCI DSS Compliant &bull; 256-bit SSL</div></div>';

  html += '</div>';

  openModal('<i class="fas fa-lock" style="color:#00B894"></i> Payment Gateway', html,
    '<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>' +
    '<button class="btn btn-p" id="pgPayBtn" onclick="processGatewayPayment(\'' + billType + '\',\'' + billId + '\')" style="min-width:160px"><i class="fas fa-lock"></i> Pay RM ' + amount.toFixed(2) + '</button>', 'sm');
}

var _selectedPaymentMethod = '';
function selectPaymentMethod(method) {
  _selectedPaymentMethod = method;
  // Reset all method borders
  var allM = document.querySelectorAll('[id^="pgm-"]');
  allM.forEach(function(el) { el.style.borderColor = 'transparent'; el.style.background = 'var(--bg3)'; el.classList.remove('pg-sel'); });
  var allR = document.querySelectorAll('[id^="pgr-"]');
  allR.forEach(function(el) { el.style.background = 'transparent'; el.style.borderColor = 'var(--bg2)'; });
  // Highlight selected
  var sel = document.getElementById('pgm-' + method);
  if (sel) { sel.style.borderColor = 'var(--p)'; sel.style.background = 'var(--card)'; sel.classList.add('pg-sel'); }
  var radio = document.getElementById('pgr-' + method);
  if (radio) { radio.style.background = 'var(--p)'; radio.style.borderColor = 'var(--p)'; }
  // Toggle sub-forms
  ['pgFpxBanks','pgCardForm','pgEwalletSel','pgQrDisplay'].forEach(function(id) { var el = document.getElementById(id); if(el) el.style.display = 'none'; });
  var showMap = { fpx: 'pgFpxBanks', card: 'pgCardForm', ewallet: 'pgEwalletSel', qr: 'pgQrDisplay' };
  var show = document.getElementById(showMap[method]);
  if (show) show.style.display = 'block';
}

async function processGatewayPayment(billType, billId) {
  if (!_selectedPaymentMethod) { toast('Please select a payment method', 'error'); return; }

  // Validate based on method
  if (_selectedPaymentMethod === 'fpx') {
    var bank = document.getElementById('pgBankSel');
    if (bank && !bank.value) { toast('Please select your bank', 'error'); return; }
  }
  if (_selectedPaymentMethod === 'card') {
    var num = document.getElementById('pgCardNum');
    var cvv = document.getElementById('pgCardCvv');
    if (num && num.value.replace(/\s/g,'').length < 13) { toast('Please enter a valid card number', 'error'); return; }
    if (cvv && cvv.value.length < 3) { toast('Please enter CVV', 'error'); return; }
  }

  // Show processing state
  var btn = document.getElementById('pgPayBtn');
  if (btn) {
    btn.disabled = true;
    btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Processing...';
    btn.style.opacity = '0.7';
  }

  var methodNames = { fpx: 'FPX Online Banking', card: 'Credit/Debit Card', ewallet: 'E-Wallet', qr: 'DuitNow QR' };
  var payMethod = _selectedPaymentMethod;

  // ---- TRY REAL STRIPE INTEGRATION FIRST ----
  if (_useAPI && billType === 'rent') {
    try {
      // Check if Stripe is configured on the server
      var status = await apiFetch('/payments/status');
      if (status && status.configured) {
        // Map frontend method to Stripe payment_method_types
        var stripeMethods = [];
        if (payMethod === 'fpx') stripeMethods = ['fpx'];
        else if (payMethod === 'card') stripeMethods = ['card'];
        else if (payMethod === 'ewallet') stripeMethods = ['grabpay'];
        else stripeMethods = ['fpx', 'card', 'grabpay'];

        // Create PaymentIntent via backend
        var intent = await apiFetch('/payments/create-intent', {
          method: 'POST',
          body: JSON.stringify({ billId: billId, paymentMethods: stripeMethods })
        });

        if (intent && intent.clientSecret) {
          // Load Stripe.js if not already loaded
          if (!window.Stripe) {
            var stripeScript = document.createElement('script');
            stripeScript.src = 'https://js.stripe.com/v3/';
            document.head.appendChild(stripeScript);
            await new Promise(function(resolve) { stripeScript.onload = resolve; stripeScript.onerror = resolve; });
          }

          if (window.Stripe) {
            // Stripe.js loaded — use it to redirect to payment page
            var stripeKey = status.publishableKey || '';
            if (stripeKey) {
              var stripe = Stripe(stripeKey);
              // For FPX, redirect to bank selection
              if (payMethod === 'fpx') {
                var bankVal = document.getElementById('pgBankSel') ? document.getElementById('pgBankSel').value.toLowerCase().replace(/\s+/g, '_') : '';
                var fpxResult = await stripe.confirmFpxPayment(intent.clientSecret, {
                  payment_method: { fpx: { bank: bankVal } },
                  return_url: window.location.origin + window.location.pathname + '?payment_success=' + billId
                });
                if (fpxResult.error) {
                  toast('Payment error: ' + fpxResult.error.message, 'error');
                  if (btn) { btn.disabled = false; btn.innerHTML = '<i class="fas fa-lock"></i> Pay'; btn.style.opacity = '1'; }
                  return;
                }
                // FPX redirects to bank page — user won't see below
                return;
              }

              // For card payments
              if (payMethod === 'card') {
                var cardResult = await stripe.confirmCardPayment(intent.clientSecret, {
                  payment_method: {
                    card: { token: 'tok_visa' }, // In production, use Stripe Elements
                    billing_details: { name: document.getElementById('pgCardName') ? document.getElementById('pgCardName').value : '' }
                  }
                });
                if (cardResult.error) {
                  toast('Payment error: ' + cardResult.error.message, 'error');
                  if (btn) { btn.disabled = false; btn.innerHTML = '<i class="fas fa-lock"></i> Pay'; btn.style.opacity = '1'; }
                  return;
                }
                if (cardResult.paymentIntent && cardResult.paymentIntent.status === 'succeeded') {
                  // Confirm with backend
                  await apiFetch('/payments/confirm/' + billId, {
                    method: 'POST',
                    body: JSON.stringify({ paymentIntentId: cardResult.paymentIntent.id })
                  });
                  showPaymentReceipt(billType, billId, payMethod, methodNames);
                  return;
                }
              }

              // For GrabPay (e-wallet)
              if (payMethod === 'ewallet') {
                var grabResult = await stripe.confirmGrabPayPayment(intent.clientSecret, {
                  return_url: window.location.origin + window.location.pathname + '?payment_success=' + billId
                });
                if (grabResult.error) {
                  toast('Payment error: ' + grabResult.error.message, 'error');
                  if (btn) { btn.disabled = false; btn.innerHTML = '<i class="fas fa-lock"></i> Pay'; btn.style.opacity = '1'; }
                  return;
                }
                // GrabPay redirects to app/page — user won't see below
                return;
              }
            }
          }
        }
        // If we got here with Stripe configured but something didn't work, fall through to simulation
        console.warn('[Payment] Stripe configured but redirect not possible, falling back to simulation');
      }
    } catch(e) {
      console.warn('[Payment] Stripe integration error, falling back to simulation:', e.message);
    }
  }

  // ---- SIMULATION FALLBACK (no Stripe configured, or demo mode) ----
  setTimeout(function() {
    if (billType === 'rent') {
      var bill = BILLS.find(function(b) { return b.id === billId; });
      if (bill) {
        bill.s = 'Paid';
        // Also trigger auto-reconnect if applicable
        if (typeof payBillWithAutoReconnect === 'function') {
          payBillWithAutoReconnect(billId);
        }
      }
    } else {
      var ubill = UTILITY_BILLS.find(function(b) { return b.id === billId; });
      if (ubill) ubill.status = 'Paid';
    }
    saveData();
    closeModal();
    showPaymentReceipt(billType, billId, payMethod, methodNames);
    toast('Payment successful! (Demo mode — no real charges)', 'success');
    pushNotif('fa-credit-card', '#00B894', 'Payment Processed', billId + ' paid via ' + (methodNames[payMethod] || 'Online'));
    _selectedPaymentMethod = '';
  }, 1500);
}

// Shared receipt display for both real and simulated payments
function showPaymentReceipt(billType, billId, payMethod, methodNames) {
  var receiptHtml = '<div style="text-align:center;padding:20px">' +
    '<div style="width:64px;height:64px;border-radius:50%;background:#00B89422;color:#00B894;display:flex;align-items:center;justify-content:center;font-size:28px;margin:0 auto 14px"><i class="fas fa-check"></i></div>' +
    '<h3 style="color:#00B894;margin-bottom:4px">Payment Successful!</h3>' +
    '<div style="font-size:11px;color:var(--t3);margin-bottom:18px">Transaction completed via ' + (methodNames[payMethod] || 'Online') + '</div>' +
    '<div class="dep-card">' +
    depRow('Bill ID', billId) +
    depRow('Amount', 'RM ' + (billType === 'rent' ? (parseInt((BILLS.find(function(b){return b.id===billId;})||{a:'0'}).a.replace(/[^\d]/g,''))||0).toFixed(2) : ((UTILITY_BILLS.find(function(b){return b.id===billId;})||{total:0}).total).toFixed(2))) +
    depRow('Method', methodNames[payMethod] || 'Online') +
    depRow('Date', new Date().toLocaleDateString('en-MY')) +
    depRow('Time', new Date().toLocaleTimeString('en-MY')) +
    depRowHtml('Status', '<span class="bs b-ok">Paid</span>') +
    depRow('Ref No.', 'WS-' + Date.now().toString(36).toUpperCase()) +
    '</div></div>';

  setTimeout(function() {
    openModal('<i class="fas fa-receipt" style="color:#00B894"></i> Payment Receipt', receiptHtml,
      '<button class="btn btn-ghost" onclick="closeModal();navigateTo(\'my-bills\')">Done</button>' +
      '<button class="btn" style="background:#00B894;color:#fff" onclick="printReportPreview()"><i class="fas fa-print"></i> Print Receipt</button>', 'sm');
  }, 200);
}

// Pay All Outstanding Bills at once
function tenantPayAllBills() {
  var tenant = ROLE_CONFIG[currentRole] ? ROLE_CONFIG[currentRole].user.name : 'Sarah Lim';
  var unpaidRent = BILLS.filter(function(b) { return b.t === tenant && b.s !== 'Paid'; });
  var unpaidUtil = typeof UTILITY_BILLS !== 'undefined' ? UTILITY_BILLS.filter(function(b) { return b.tenant === tenant && b.status !== 'Paid'; }) : [];
  var totalAmt = 0;
  unpaidRent.forEach(function(b) { totalAmt += parseInt(b.a.replace(/[^\d]/g, '')) || 0; });
  unpaidUtil.forEach(function(b) { totalAmt += b.total; });

  if (totalAmt === 0) { toast('No outstanding bills!', 'info'); return; }

  var count = unpaidRent.length + unpaidUtil.length;
  confirmDialog('Pay All Bills?', 'Process payment for all ' + count + ' outstanding bill(s) totaling RM ' + totalAmt.toFixed(2) + '? This will open the payment gateway.', function() {
    // Open gateway for the total
    var html = '<div style="max-width:420px;margin:0 auto">';
    html += '<div style="background:linear-gradient(135deg,#6C5CE7,#00B894);padding:22px;border-radius:16px;text-align:center;margin-bottom:18px">' +
      '<div style="font-size:28px;margin-bottom:4px">\uD83D\uDD12</div>' +
      '<h3 style="color:#fff;font-size:15px;margin-bottom:2px">BULK PAYMENT</h3>' +
      '<div style="color:rgba(255,255,255,.7);font-size:11px">Pay all outstanding bills at once</div></div>';

    html += '<div style="text-align:center;padding:18px;background:var(--bg3);border-radius:14px;margin-bottom:16px">' +
      '<div style="font-size:10px;color:var(--t3);margin-bottom:4px">' + count + ' bill(s)</div>' +
      '<div style="font-size:32px;font-weight:800;color:var(--p)">RM ' + totalAmt.toFixed(2) + '</div></div>';

    // List bills being paid
    html += '<div style="margin-bottom:14px;max-height:150px;overflow-y:auto">';
    unpaidRent.forEach(function(b) {
      html += '<div style="display:flex;align-items:center;gap:8px;padding:6px 10px;background:var(--bg3);border-radius:8px;margin-bottom:4px;font-size:11px">' +
        '<i class="fas fa-home" style="color:#6C5CE7"></i><span style="flex:1">' + escHtml(b.id) + ' — Rent</span><span style="font-weight:600">' + escHtml(b.a) + '</span></div>';
    });
    unpaidUtil.forEach(function(b) {
      html += '<div style="display:flex;align-items:center;gap:8px;padding:6px 10px;background:var(--bg3);border-radius:8px;margin-bottom:4px;font-size:11px">' +
        '<i class="fas fa-bolt" style="color:#FDCB6E"></i><span style="flex:1">' + escHtml(b.id) + ' — Utility</span><span style="font-weight:600">RM ' + b.total.toFixed(2) + '</span></div>';
    });
    html += '</div>';

    // Payment method (simplified — FPX only for bulk)
    html += '<div style="font-size:12px;font-weight:600;margin-bottom:8px"><i class="fas fa-wallet" style="color:var(--p);margin-right:6px"></i>Payment Method</div>';
    html += '<div class="form-group"><select id="pgBulkMethod">' +
      '<option value="fpx">FPX Online Banking</option>' +
      '<option value="card">Credit / Debit Card</option>' +
      '<option value="ewallet">E-Wallet (TnG / GrabPay / Boost)</option></select></div>';

    html += '<div style="display:flex;align-items:center;gap:8px;padding:10px;background:var(--bg3);border-radius:10px">' +
      '<i class="fas fa-shield-alt" style="color:var(--ok);font-size:14px"></i>' +
      '<div style="font-size:10px;color:var(--t3)">Secured by WeStay Payment Gateway &bull; PCI DSS Compliant</div></div>';
    html += '</div>';

    closeModal();
    setTimeout(function() {
      openModal('<i class="fas fa-lock" style="color:#00B894"></i> Pay All Bills', html,
        '<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>' +
        '<button class="btn btn-p" id="pgBulkPayBtn" onclick="processBulkPayment()"><i class="fas fa-lock"></i> Pay RM ' + totalAmt.toFixed(2) + '</button>', 'sm');
    }, 200);
  }, 'success');
}

function processBulkPayment() {
  var btn = document.getElementById('pgBulkPayBtn');
  if (btn) { btn.disabled = true; btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Processing...'; btn.style.opacity = '0.7'; }

  var tenant = ROLE_CONFIG[currentRole] ? ROLE_CONFIG[currentRole].user.name : 'Sarah Lim';

  setTimeout(function() {
    var count = 0;
    BILLS.forEach(function(b) { if (b.t === tenant && b.s !== 'Paid') { b.s = 'Paid'; count++; } });
    if (typeof UTILITY_BILLS !== 'undefined') {
      UTILITY_BILLS.forEach(function(b) { if (b.tenant === tenant && b.status !== 'Paid') { b.status = 'Paid'; count++; } });
    }
    saveData();
    closeModal();
    toast(count + ' bill(s) paid successfully!', 'success');
    pushNotif('fa-credit-card', '#00B894', 'Bulk Payment', count + ' bills paid');
    navigateTo('my-bills');
  }, 1500);
}

// Preview My Bills Report
function previewMyBillsReport() {
  var tenant = ROLE_CONFIG[currentRole] ? ROLE_CONFIG[currentRole].user.name : 'Sarah Lim';
  var myRentBills = BILLS.filter(function(b) { return b.t === tenant; });
  var myUtilBills = typeof UTILITY_BILLS !== 'undefined' ? UTILITY_BILLS.filter(function(b) { return b.tenant === tenant; }) : [];
  var now = new Date();
  var monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];

  var totalRent = 0, totalUtil = 0, totalPaid = 0;
  myRentBills.forEach(function(b) { var amt = parseInt(b.a.replace(/[^\d]/g,''))||0; totalRent += amt; if(b.s==='Paid') totalPaid += amt; });
  myUtilBills.forEach(function(b) { totalUtil += b.total; if(b.status==='Paid') totalPaid += b.total; });

  var html = '<div style="max-width:650px;margin:0 auto">';
  // Header
  html += '<div style="background:linear-gradient(135deg,#6C5CE7,#74B9FF);padding:24px;border-radius:16px;text-align:center;margin-bottom:18px">' +
    '<div style="font-size:28px;margin-bottom:4px">\uD83D\uDCCB</div>' +
    '<h3 style="color:#fff;font-size:16px;margin-bottom:2px">TENANT BILLING STATEMENT</h3>' +
    '<div style="color:rgba(255,255,255,.7);font-size:12px">' + escHtml(tenant) + ' &bull; ' + monthNames[now.getMonth()] + ' ' + now.getFullYear() + '</div></div>';

  // Summary
  html += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px;margin-bottom:16px">' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:12px"><div style="font-size:18px;font-weight:800;color:#6C5CE7">RM ' + totalRent + '</div><div style="font-size:10px;color:var(--t3)">Total Rent</div></div>' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:12px"><div style="font-size:18px;font-weight:800;color:#FDCB6E">RM ' + totalUtil.toFixed(2) + '</div><div style="font-size:10px;color:var(--t3)">Total Utility</div></div>' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:12px"><div style="font-size:18px;font-weight:800;color:#00B894">RM ' + totalPaid.toFixed(2) + '</div><div style="font-size:10px;color:var(--t3)">Paid</div></div>' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:12px"><div style="font-size:18px;font-weight:800;color:#E17055">RM ' + (totalRent + totalUtil - totalPaid).toFixed(2) + '</div><div style="font-size:10px;color:var(--t3)">Outstanding</div></div></div>';

  // Rent bills table
  if (myRentBills.length) {
    html += '<div style="margin-bottom:14px"><div style="font-size:12px;font-weight:600;margin-bottom:8px"><i class="fas fa-home" style="color:#6C5CE7;margin-right:6px"></i>Rental Invoices</div>';
    html += '<table><thead><tr><th>Invoice</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>';
    myRentBills.forEach(function(b) {
      var cls = b.s === 'Paid' ? 'b-ok' : b.s === 'Pending' ? 'b-warn' : 'b-err';
      html += '<tr><td style="font-weight:600">' + escHtml(b.id) + '</td><td>' + escHtml(b.a) + '</td><td><span class="bs ' + cls + '">' + escHtml(b.s) + '</span></td><td>' + escHtml(b.d) + '</td></tr>';
    });
    html += '</tbody></table></div>';
  }

  // Utility bills table
  if (myUtilBills.length) {
    html += '<div style="margin-bottom:14px"><div style="font-size:12px;font-weight:600;margin-bottom:8px"><i class="fas fa-bolt" style="color:#FDCB6E;margin-right:6px"></i>Utility Bills</div>';
    html += '<table><thead><tr><th>Bill ID</th><th>Period</th><th>Electricity</th><th>Water</th><th>Internet</th><th>Sewerage</th><th>Total</th><th>Status</th></tr></thead><tbody>';
    myUtilBills.forEach(function(b) {
      var cls = b.status === 'Paid' ? 'b-ok' : 'b-warn';
      var getAmt = function(type) { var item = b.items.find(function(i){return i.type===type;}); return item ? 'RM ' + item.amount.toFixed(2) : '-'; };
      html += '<tr><td style="font-weight:600">' + escHtml(b.id) + '</td><td>' + escHtml(b.period) + '</td>' +
        '<td>' + getAmt('Electricity') + '</td><td>' + getAmt('Water') + '</td>' +
        '<td>' + getAmt('Internet') + '</td><td>' + getAmt('Sewerage') + '</td>' +
        '<td style="font-weight:600">RM ' + b.total.toFixed(2) + '</td><td><span class="bs ' + cls + '">' + escHtml(b.status) + '</span></td></tr>';
    });
    html += '</tbody></table></div>';
  }

  // Grand total
  html += '<div style="padding:14px;background:var(--bg3);border-radius:12px;border-left:3px solid var(--p)">' +
    '<div style="display:flex;justify-content:space-between;align-items:center">' +
    '<div style="font-size:13px;font-weight:700">Grand Total</div>' +
    '<div style="font-size:20px;font-weight:800;color:var(--p)">RM ' + (totalRent + totalUtil).toFixed(2) + '</div></div></div>';

  html += '<div style="text-align:center;padding:12px;font-size:10px;color:var(--t3);margin-top:12px">Generated by WeStay &bull; ' + now.toLocaleDateString('en-MY') + '</div></div>';

  openModal('<i class="fas fa-file-alt" style="color:#6C5CE7"></i> Billing Statement — ' + escHtml(tenant), html,
    '<button class="btn btn-ghost" onclick="closeModal()">Close</button>' +
    '<button class="btn btn-p" onclick="exportMyBillsCSV()"><i class="fas fa-download"></i> Export CSV</button>' +
    '<button class="btn" style="background:#00B894;color:#fff" onclick="printReportPreview()"><i class="fas fa-print"></i> Print / PDF</button>', 'lg');
}

// Export tenant's combined bills as CSV
function exportMyBillsCSV() {
  var tenant = ROLE_CONFIG[currentRole] ? ROLE_CONFIG[currentRole].user.name : 'Sarah Lim';
  var headers = ['Bill ID','Type','Amount (RM)','Status','Date/Period','Details'];
  var rows = [];
  BILLS.filter(function(b){return b.t===tenant;}).forEach(function(b) {
    rows.push([b.id, 'Rent', b.a, b.s, b.d, b.prop || '']);
  });
  if (typeof UTILITY_BILLS !== 'undefined') {
    UTILITY_BILLS.filter(function(b){return b.tenant===tenant;}).forEach(function(b) {
      var details = b.items.map(function(i){return i.type+': RM '+i.amount.toFixed(2);}).join('; ');
      rows.push([b.id, 'Utility', 'RM ' + b.total.toFixed(2), b.status, b.period, details]);
    });
  }
  exportCSV(headers, rows, 'my-bills-' + tenant.replace(/\s+/g,'-').toLowerCase() + '-' + new Date().toISOString().slice(0,7) + '.csv');
  toast('Bills exported to CSV', 'success');
}

// Tenant view of their utility bills — shows ALL months, paid & unpaid
function tenantViewUtilityBills() {
  var tenant = ROLE_CONFIG[currentRole] ? ROLE_CONFIG[currentRole].user.name : 'Sarah Lim';
  var myBills = typeof UTILITY_BILLS !== 'undefined' ? UTILITY_BILLS.filter(function(b) { return b.tenant === tenant; }) : [];

  if (!myBills.length) {
    toast('No utility bills found. Bills are generated by your property manager.', 'info');
    return;
  }

  // Sort by date descending (newest first)
  var sorted = myBills.slice().sort(function(a, b) {
    return (b.date || '').localeCompare(a.date || '');
  });

  // Summary stats
  var totalBills = sorted.length;
  var paidBills = sorted.filter(function(b) { return b.status === 'Paid'; });
  var unpaidBills = sorted.filter(function(b) { return b.status !== 'Paid'; });
  var totalAmount = sorted.reduce(function(s, b) { return s + b.total; }, 0);
  var totalPaid = paidBills.reduce(function(s, b) { return s + b.total; }, 0);
  var totalUnpaid = unpaidBills.reduce(function(s, b) { return s + b.total; }, 0);

  var html = '';

  // Summary header
  html += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px;margin-bottom:16px">' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--p)">' + totalBills + '</div><div style="font-size:10px;color:var(--t3)">All Bills</div></div>' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--ok)">' + paidBills.length + '</div><div style="font-size:10px;color:var(--t3)">Paid</div></div>' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--warn)">' + unpaidBills.length + '</div><div style="font-size:10px;color:var(--t3)">Unpaid</div></div>' +
    '<div style="text-align:center;padding:12px;background:var(--bg3);border-radius:10px"><div style="font-size:18px;font-weight:700;color:var(--p)">RM ' + totalAmount.toFixed(2) + '</div><div style="font-size:10px;color:var(--t3)">Total</div></div></div>';

  // Filter tabs
  html += '<div style="display:flex;gap:8px;margin-bottom:14px">' +
    '<button class="btn-s" style="background:var(--p);color:#fff" onclick="filterUtilBills(\'all\')">All (' + totalBills + ')</button>' +
    '<button class="btn-s" onclick="filterUtilBills(\'unpaid\')" id="ubFilterUnpaid">Unpaid (' + unpaidBills.length + ')</button>' +
    '<button class="btn-s" onclick="filterUtilBills(\'paid\')" id="ubFilterPaid">Paid (' + paidBills.length + ')</button></div>';

  // Bill cards — all months
  html += '<div id="ubCardList">';
  sorted.forEach(function(bill) {
    var isPaid = bill.status === 'Paid';
    var borderColor = isPaid ? '#00B894' : '#FDCB6E';
    html += '<div class="ub-card" data-status="' + (isPaid ? 'paid' : 'unpaid') + '" style="background:var(--bg3);border-radius:14px;padding:16px;margin-bottom:12px;border-left:3px solid ' + borderColor + '">';

    // Bill header row
    html += '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px">' +
      '<div style="display:flex;align-items:center;gap:10px">' +
      '<div style="width:36px;height:36px;border-radius:10px;background:' + borderColor + '22;color:' + borderColor + ';display:flex;align-items:center;justify-content:center;font-size:14px"><i class="fas ' + (isPaid ? 'fa-check-circle' : 'fa-clock') + '"></i></div>' +
      '<div><div style="font-size:13px;font-weight:700">' + escHtml(bill.period) + '</div>' +
      '<div style="font-size:10px;color:var(--t3)">' + escHtml(bill.id) + ' &bull; ' + escHtml(bill.date) + '</div></div></div>' +
      '<div style="text-align:right"><div style="font-size:18px;font-weight:800;color:var(--p)">RM ' + bill.total.toFixed(2) + '</div>' +
      '<span class="bs ' + (isPaid ? 'b-ok' : 'b-warn') + '" style="font-size:9px">' + escHtml(bill.status) + '</span></div></div>';

    // Charge breakdown grid
    html += '<div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:6px">';
    bill.items.forEach(function(item) {
      var ic = item.type === 'Electricity' ? 'fa-bolt' : item.type === 'Water' ? 'fa-tint' : item.type === 'Internet' ? 'fa-wifi' : 'fa-shower';
      var col = item.type === 'Electricity' ? '#FDCB6E' : item.type === 'Water' ? '#74B9FF' : item.type === 'Internet' ? '#6C5CE7' : '#A29BFE';
      html += '<div style="padding:8px;background:var(--bg2);border-radius:8px;text-align:center">' +
        '<i class="fas ' + ic + '" style="color:' + col + ';font-size:12px;display:block;margin-bottom:4px"></i>' +
        '<div style="font-size:9px;color:var(--t3)">' + escHtml(item.type) + '</div>' +
        '<div style="font-size:11px;font-weight:600">RM ' + item.amount.toFixed(2) + '</div>';
      if (item.usage && item.unit && item.unit !== 'month') {
        html += '<div style="font-size:8px;color:var(--t3)">' + item.usage + ' ' + escHtml(item.unit) + '</div>';
      }
      html += '</div>';
    });
    html += '</div>';

    // View detail button (no payment gateway here)
    html += '<div style="margin-top:10px;text-align:right"><button class="btn-s" onclick="showUtilityBillDetail(\'' + bill.id + '\')"><i class="fas fa-eye"></i> View Details</button></div>';

    html += '</div>';
  });
  html += '</div>';

  // Rate reference footer
  html += '<div style="padding:10px;background:var(--bg3);border-radius:10px;font-size:10px;color:var(--t3);margin-top:8px">' +
    '<strong>Rate Reference:</strong> Electric: RM ' + UTILITY_RATES.electric.rate + '/kWh &bull; ' +
    'Water: RM ' + UTILITY_RATES.water.rate + '/m\u00B3 &bull; ' +
    'Internet: RM ' + UTILITY_RATES.internet.rate + '/month &bull; ' +
    'Sewerage: RM ' + UTILITY_RATES.sewerage.rate + '/month</div>';

  openModal('<i class="fas fa-bolt" style="color:#74B9FF"></i> My Utility Bills — All Months', html,
    '<button class="btn btn-ghost" onclick="closeModal()">Close</button>', 'lg');
}

// Filter utility bill cards by status
function filterUtilBills(filter) {
  var cards = document.querySelectorAll('.ub-card');
  cards.forEach(function(card) {
    if (filter === 'all') { card.style.display = ''; }
    else { card.style.display = card.getAttribute('data-status') === filter ? '' : 'none'; }
  });
}


// ============================================================
// 3. PHOTO ATTACHMENTS — Tickets + Check-In/Check-Out
// ============================================================

// Photo storage uses simulated file names (since this is a demo without a real server)
// In production, these would be URLs from a file upload API

function showTicketPhotos(ticketId) {
  var photos = TICKET_PHOTOS[ticketId] || [];
  var tk = TICKETS.find(function(t) { return t.id === ticketId; });

  var html = '<div style="margin-bottom:14px;font-size:12px;color:var(--t2)">' +
    'Photos attached to ticket <strong>' + escHtml(ticketId) + '</strong>' +
    (tk ? ' — ' + escHtml(tk.t) : '') + '</div>';

  if (photos.length) {
    html += '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:10px;margin-bottom:14px">';
    photos.forEach(function(photo, i) {
      // Simulate photo thumbnail with colored placeholder
      var color = COLORS[i % 8];
      html += '<div style="position:relative;background:' + color + '22;border:1px solid ' + color + '44;border-radius:12px;padding:30px 10px;text-align:center;cursor:pointer" onclick="viewPhoto(\'' + escHtml(photo) + '\')">' +
        '<i class="fas fa-image" style="font-size:28px;color:' + color + ';display:block;margin-bottom:8px"></i>' +
        '<div style="font-size:10px;color:var(--t2);word-break:break-all">' + escHtml(photo) + '</div>' +
        '<button class="btn-s" style="position:absolute;top:6px;right:6px;font-size:9px;padding:2px 6px" onclick="event.stopPropagation();removeTicketPhoto(\'' + ticketId + '\',' + i + ')"><i class="fas fa-times"></i></button></div>';
    });
    html += '</div>';
  } else {
    html += '<div class="empty-state" style="padding:20px"><i class="fas fa-camera" style="font-size:28px"></i><p>No photos attached yet</p></div>';
  }

  html += '<div style="display:flex;gap:8px">' +
    '<button class="btn btn-p" style="flex:1" onclick="addTicketPhoto(\'' + ticketId + '\')"><i class="fas fa-camera"></i> Add Photo</button>' +
    '<button class="btn btn-ghost" style="flex:1" onclick="closeModal()">Close</button></div>';

  openModal('<i class="fas fa-images" style="color:#FD79A8"></i> Ticket Photos — ' + escHtml(ticketId), html, '', 'sm');
}

function addTicketPhoto(ticketId) {
  // Create a hidden file input
  var input = document.createElement('input');
  input.type = 'file';
  input.accept = 'image/*';
  input.multiple = true;
  input.onchange = function() {
    if (!input.files || !input.files.length) return;
    if (!TICKET_PHOTOS[ticketId]) TICKET_PHOTOS[ticketId] = [];
    for (var i = 0; i < input.files.length; i++) {
      var file = input.files[i];
      // Store the file name (in production: upload to server and store URL)
      TICKET_PHOTOS[ticketId].push(file.name);
    }
    saveData();
    toast(input.files.length + ' photo(s) attached to ' + ticketId, 'success');
    pushNotif('fa-camera', '#FD79A8', 'Photo Attached', input.files.length + ' photo(s) added to ' + ticketId);
    closeModal();
    setTimeout(function() { showTicketPhotos(ticketId); }, 200);
  };
  input.click();
}

function removeTicketPhoto(ticketId, index) {
  confirmDialog('Remove Photo?', 'Remove this photo from ticket ' + escHtml(ticketId) + '?', function() {
    if (TICKET_PHOTOS[ticketId]) {
      TICKET_PHOTOS[ticketId].splice(index, 1);
      saveData();
      toast('Photo removed', 'info');
      closeModal();
      setTimeout(function() { showTicketPhotos(ticketId); }, 200);
    }
  }, 'danger');
}

function viewPhoto(filename) {
  // Simulated photo viewer
  var color = COLORS[Math.floor(Math.random() * COLORS.length)];
  openModal('<i class="fas fa-image" style="color:#FD79A8"></i> ' + escHtml(filename),
    '<div style="text-align:center;padding:30px"><div style="width:100%;height:280px;background:linear-gradient(135deg,' + color + '22,' + color + '08);border-radius:14px;display:flex;flex-direction:column;align-items:center;justify-content:center">' +
    '<i class="fas fa-image" style="font-size:60px;color:' + color + ';margin-bottom:12px"></i>' +
    '<div style="font-size:13px;font-weight:600;color:var(--t2)">' + escHtml(filename) + '</div>' +
    '<div style="font-size:10px;color:var(--t3);margin-top:6px">(Photo preview — simulated in demo)</div></div></div>',
    '<button class="btn btn-ghost" onclick="closeModal()">Close</button>', 'sm');
}

// ---- CHECK-IN / CHECK-OUT WORKFLOW ----

// Tenant-only: shows only current tenant's check-in/out records
function showMyCheckInOutList() {
  var tenant = ROLE_CONFIG[currentRole] ? ROLE_CONFIG[currentRole].user.name : 'Sarah Lim';
  var myRecords = CHECKINOUT_RECORDS.filter(function(r) { return r.tenant === tenant; });

  var html = '<div style="margin-bottom:14px;font-size:12px;color:var(--t2)"><i class="fas fa-info-circle" style="color:var(--p);margin-right:6px"></i>Your unit check-in and check-out photo records.</div>';

  if (!myRecords.length) {
    html += '<div class="empty-state"><i class="fas fa-clipboard-check"></i><p>No check-in/check-out records for your unit.</p></div>';
  } else {
    html += '<table><thead><tr><th>ID</th><th>Unit</th><th>Type</th><th>Date</th><th>Photos</th><th>Status</th><th></th></tr></thead><tbody>';
    myRecords.forEach(function(rec) {
      var cls = rec.status === 'Completed' ? 'b-ok' : 'b-warn';
      var typeCls = rec.type === 'check-in' ? 'b-info' : 'b-warn';
      html += '<tr><td style="font-weight:600">' + escHtml(rec.id) + '</td>' +
        '<td>' + escHtml(rec.unit) + '</td>' +
        '<td><span class="bs ' + typeCls + '">' + escHtml(rec.type.toUpperCase()) + '</span></td>' +
        '<td>' + escHtml(rec.date) + '</td>' +
        '<td>' + (rec.photos ? rec.photos.length : 0) + ' <i class="fas fa-image" style="font-size:10px;color:var(--t3)"></i></td>' +
        '<td><span class="bs ' + cls + '">' + escHtml(rec.status) + '</span></td>' +
        '<td><button class="btn-s" onclick="showCheckInOutDetail(\'' + rec.id + '\')"><i class="fas fa-eye"></i></button></td></tr>';
    });
    html += '</tbody></table>';
  }

  openModal('<i class="fas fa-clipboard-check" style="color:#00CEC9"></i> My Check-In / Check-Out Records', html, '<button class="btn btn-ghost" onclick="closeModal()">Close</button>', 'lg');
}

function showCheckInOutList() {
  var html = '<div style="margin-bottom:14px;display:flex;align-items:center;justify-content:space-between">' +
    '<div style="font-size:12px;color:var(--t2)"><i class="fas fa-info-circle" style="color:var(--p);margin-right:6px"></i>Document unit conditions with photos during tenant check-in and check-out.</div>' +
    '<button class="btn btn-p" onclick="closeModal();startCheckInOut()" style="flex-shrink:0"><i class="fas fa-plus"></i> New Inspection</button></div>';

  if (!CHECKINOUT_RECORDS.length) {
    html += '<div class="empty-state"><i class="fas fa-clipboard-check"></i><p>No check-in/check-out records yet.</p></div>';
  } else {
    html += '<table><thead><tr><th>ID</th><th>Tenant</th><th>Unit</th><th>Type</th><th>Date</th><th>Photos</th><th>Status</th><th></th></tr></thead><tbody>';
    CHECKINOUT_RECORDS.forEach(function(rec) {
      var cls = rec.status === 'Completed' ? 'b-ok' : 'b-warn';
      var typeCls = rec.type === 'check-in' ? 'b-info' : 'b-warn';
      html += '<tr><td style="font-weight:600">' + escHtml(rec.id) + '</td>' +
        '<td>' + escHtml(rec.tenant) + '</td>' +
        '<td>' + escHtml(rec.unit) + '</td>' +
        '<td><span class="bs ' + typeCls + '">' + escHtml(rec.type.toUpperCase()) + '</span></td>' +
        '<td>' + escHtml(rec.date) + '</td>' +
        '<td>' + (rec.photos ? rec.photos.length : 0) + ' <i class="fas fa-image" style="font-size:10px;color:var(--t3)"></i></td>' +
        '<td><span class="bs ' + cls + '">' + escHtml(rec.status) + '</span></td>' +
        '<td><button class="btn-s" onclick="showCheckInOutDetail(\'' + rec.id + '\')"><i class="fas fa-eye"></i></button></td></tr>';
    });
    html += '</tbody></table>';
  }

  openModal('<i class="fas fa-clipboard-check" style="color:#00CEC9"></i> Check-In / Check-Out Records', html, '<button class="btn btn-ghost" onclick="closeModal()">Close</button>', 'lg');
}

function startCheckInOut() {
  var tenantOpts = TENANTS.map(function(t) { return '<option value="' + escHtml(t.n) + '">' + escHtml(t.n) + ' — ' + escHtml(t.p) + '</option>'; }).join('');
  openModal('<i class="fas fa-clipboard-check" style="color:#00CEC9"></i> New Inspection',
    '<div class="form-group"><label>Tenant</label><select id="cioTenant">' + tenantOpts + '</select></div>' +
    '<div class="form-group"><label>Type</label><select id="cioType"><option value="check-in">Check-In</option><option value="check-out">Check-Out</option></select></div>' +
    '<div class="form-group"><label>Date</label><input type="date" id="cioDate" value="' + new Date().toISOString().slice(0, 10) + '"></div>' +
    '<div class="form-group"><label>Inspector</label><input id="cioInspector" value="Admin Operator" placeholder="Inspector name"></div>' +
    '<div class="form-group"><label>Notes</label><textarea id="cioNotes" placeholder="Condition notes..."></textarea></div>',
    '<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>' +
    '<button class="btn btn-p" onclick="doCreateCheckInOut()"><i class="fas fa-check"></i> Create & Add Photos</button>', 'sm');
}

function doCreateCheckInOut() {
  var tenantName = document.getElementById('cioTenant').value;
  var tenant = TENANTS.find(function(t) { return t.n === tenantName; });
  if (!tenant) { toast('Select a tenant', 'error'); return; }

  var rec = {
    id: 'CIO-' + String(CHECKINOUT_RECORDS.length + 1).padStart(3, '0'),
    tenant: tenant.n,
    unit: tenant.p,
    type: document.getElementById('cioType').value,
    date: document.getElementById('cioDate').value || new Date().toISOString().slice(0, 10),
    inspector: sanitizeInput(document.getElementById('cioInspector').value) || 'Admin Operator',
    status: 'In Progress',
    notes: sanitizeInput(document.getElementById('cioNotes').value) || '',
    photos: []
  };

  CHECKINOUT_RECORDS.push(rec);
  saveData();
  toast(rec.type.replace('-', ' ').toUpperCase() + ' record created for ' + escHtml(tenant.n), 'success');
  pushNotif('fa-clipboard-check', '#00CEC9', rec.type.toUpperCase(), escHtml(tenant.n) + ' — ' + escHtml(tenant.p));

  closeModal();
  setTimeout(function() { showCheckInOutDetail(rec.id); }, 200);
}

function showCheckInOutDetail(recId) {
  var rec = CHECKINOUT_RECORDS.find(function(r) { return r.id === recId; });
  if (!rec) { toast('Record not found', 'error'); return; }

  var html = '<div class="dep-card">' +
    depRow('ID', escHtml(rec.id)) +
    depRow('Tenant', escHtml(rec.tenant)) +
    depRow('Unit', escHtml(rec.unit)) +
    depRowHtml('Type', '<span class="bs ' + (rec.type === 'check-in' ? 'b-info' : 'b-warn') + '">' + escHtml(rec.type.toUpperCase()) + '</span>') +
    depRow('Date', escHtml(rec.date)) +
    depRow('Inspector', escHtml(rec.inspector || 'N/A')) +
    depRowHtml('Status', '<span class="bs ' + (rec.status === 'Completed' ? 'b-ok' : 'b-warn') + '">' + escHtml(rec.status) + '</span>') +
    '</div>';

  if (rec.notes) {
    html += '<div style="margin:12px 0"><div style="font-size:11px;font-weight:600;margin-bottom:6px;color:var(--t2)"><i class="fas fa-sticky-note" style="color:var(--warn);margin-right:6px"></i>Notes</div>' +
      '<div style="padding:10px;background:var(--bg3);border-radius:10px;font-size:12px;color:var(--t2);line-height:1.5">' + escHtml(rec.notes) + '</div></div>';
  }

  // Photos section
  html += '<div style="margin:12px 0"><div style="font-size:11px;font-weight:600;margin-bottom:8px;color:var(--t2)"><i class="fas fa-camera" style="color:#FD79A8;margin-right:6px"></i>Photos (' + (rec.photos ? rec.photos.length : 0) + ')</div>';

  if (rec.photos && rec.photos.length) {
    html += '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:8px">';
    rec.photos.forEach(function(photo, i) {
      var color = COLORS[i % 8];
      html += '<div style="position:relative;background:' + color + '22;border:1px solid ' + color + '44;border-radius:10px;padding:20px 8px;text-align:center;cursor:pointer" onclick="viewPhoto(\'' + escHtml(photo) + '\')">' +
        '<i class="fas fa-image" style="font-size:22px;color:' + color + ';display:block;margin-bottom:6px"></i>' +
        '<div style="font-size:9px;color:var(--t3);word-break:break-all">' + escHtml(photo) + '</div>' +
        '<button class="btn-s" style="position:absolute;top:4px;right:4px;font-size:8px;padding:2px 5px" onclick="event.stopPropagation();removeCioPhoto(\'' + recId + '\',' + i + ')"><i class="fas fa-times"></i></button></div>';
    });
    html += '</div>';
  } else {
    html += '<div style="text-align:center;padding:16px;background:var(--bg3);border-radius:10px;color:var(--t3);font-size:11px"><i class="fas fa-camera" style="display:block;font-size:20px;margin-bottom:6px"></i>No photos yet — add photos to document the unit condition</div>';
  }
  html += '</div>';

  // Actions
  html += '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px">';
  html += '<button class="btn btn-p" onclick="addCioPhoto(\'' + recId + '\')"><i class="fas fa-camera"></i> Add Photos</button>';
  if (rec.status !== 'Completed') {
    html += '<button class="btn btn-ok" onclick="completeCio(\'' + recId + '\')"><i class="fas fa-check"></i> Mark Complete</button>';
  } else {
    html += '<button class="btn btn-ghost" onclick="closeModal();showCheckInOutList()"><i class="fas fa-arrow-left"></i> Back to List</button>';
  }
  html += '</div>';

  closeModal();
  setTimeout(function() {
    openModal('<i class="fas fa-clipboard-check" style="color:#00CEC9"></i> ' + escHtml(rec.type.toUpperCase()) + ' — ' + escHtml(rec.tenant), html,
      '<button class="btn btn-ghost" onclick="closeModal();showCheckInOutList()">Back</button>', 'sm');
  }, 200);
}

function addCioPhoto(recId) {
  var rec = CHECKINOUT_RECORDS.find(function(r) { return r.id === recId; });
  if (!rec) return;
  var input = document.createElement('input');
  input.type = 'file';
  input.accept = 'image/*';
  input.multiple = true;
  input.onchange = function() {
    if (!input.files || !input.files.length) return;
    if (!rec.photos) rec.photos = [];
    for (var i = 0; i < input.files.length; i++) {
      rec.photos.push(input.files[i].name);
    }
    saveData();
    toast(input.files.length + ' photo(s) added to ' + escHtml(rec.id), 'success');
    closeModal();
    setTimeout(function() { showCheckInOutDetail(recId); }, 200);
  };
  input.click();
}

function removeCioPhoto(recId, index) {
  confirmDialog('Remove Photo?', 'Remove this photo from the inspection record?', function() {
    var rec = CHECKINOUT_RECORDS.find(function(r) { return r.id === recId; });
    if (rec && rec.photos) {
      rec.photos.splice(index, 1);
      saveData();
      toast('Photo removed', 'info');
      closeModal();
      setTimeout(function() { showCheckInOutDetail(recId); }, 200);
    }
  }, 'danger');
}

function completeCio(recId) {
  confirmDialog('Complete Inspection?', 'Mark this check-in/check-out inspection as completed?', function() {
    var rec = CHECKINOUT_RECORDS.find(function(r) { return r.id === recId; });
    if (rec) {
      rec.status = 'Completed';
      saveData();
      toast('Inspection ' + escHtml(rec.id) + ' completed!', 'success');
      closeModal();
      setTimeout(function() { showCheckInOutDetail(recId); }, 200);
    }
  }, 'success');
}
